name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: HamidSadi
          outputs: |
            snake.svg

      - name: Upload snake as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-snake
          path: snake.svg
