name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily at midnight
  workflow_dispatch:      # allows manual trigger

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: HamidSadi
          # output path can be gif or svg
          outputs: |
            dist/github-contribution-snake.svg

      - name: Commit & Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Update GitHub contribution snake"
          add: "dist/github-contribution-snake.svg"
